version: '3.3'
services:
    
    database:
        image: mysql:5.7
        volumes:
            - data:/var/lib/mysql
        ports:
            - "3306:3306"
        networks:
            - network
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: wordpress
            MYSQL_USER: root
            MYSQL_PASSWORD: secret

    app:
        depends_on:
            - database
        image: wordpress:5.3.0-php7.2-fpm
        volumes:
            - ./:/var/www/html
        networks:
            - network
        restart: always
        environment:
            WORDPRESS_DB_HOST: database:3306
            WORDPRESS_DB_USER: root
            WORDPRESS_DB_PASSWORD: secret
            WORDPRESS_DB_NAME: wordpress

    web:
        depends_on:
            - app
        image: nginx:1.15.8
        volumes:
            - ./:/var/www/html
            - .nginx:/etc/nginx/conf.d/default.conf
            - ./wp-ssl/local.cert:/etc/ssl/certs/local.cert
            - ./wp-ssl/local.key:/etc/ssl/certs/local.key
        ports:
            - "8080:80"
            - "8443:443"
        networks:
            - network

volumes:
    data:

networks:
    network:
        driver: bridge